---
all:
  children:
    web_servers:
      hosts:
        frontend:
          ansible_host: "{{ vars }}"
          ansible_user: ubuntu
          ansible_connection: ssh
        backend:
          ansible_host: "{{ vars }}"
          ansible_user: ubuntu
          ansible_connection: ssh
    db_servers:
      hosts:
        database:
          ansible_host: "{{ vars }}"
          ansible_user: ubuntu
          ansible_connection: ssh